# Generated by Django 2.2.7 on 2020-03-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя приложения')),
                ('key_api', models.CharField(max_length=200, verbose_name='Ключ для авторизации к приложению')),
            ],
        ),
    ]
